/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.User;
import Model.Contact;
import Model.Recipe;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;

/**
 *
 * @author sruthisivasankar
 */
public class CreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJpanel
     */
    private User user;
    private ArrayList<String>existingUserName;
    
//    private Boolean validate = false;
    
    public CreateJpanel() {
        initComponents();
    }

    CreateJpanel(User user, ArrayList existingUserName){
        initComponents();
        
        this.user = user;
        this.existingUserName=existingUserName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btngrpgluten = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FrstNameTxtField = new javax.swing.JTextField();
        LastNameTxtField = new javax.swing.JTextField();
        UserNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mailIdTxtField = new javax.swing.JTextField();
        phoneTxtField = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        recipeTitleTxtField = new javax.swing.JTextField();
        difficultyTxtField = new javax.swing.JTextField();
        servingSpinner = new javax.swing.JSpinner();
        btnGlutenYes = new javax.swing.JRadioButton();
        btnGlutenNo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        ingredientSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        categoryTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        descTxtField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        imagePathTxt = new javax.swing.JTextField();
        btnSaveRecipe = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        txtgluten = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel1.setText("About Chef:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Username:");

        FrstNameTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FrstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrstNameTxtFieldActionPerformed(evt);
            }
        });
        FrstNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FrstNameTxtFieldKeyReleased(evt);
            }
        });

        LastNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTxtFieldActionPerformed(evt);
            }
        });
        LastNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameTxtFieldKeyReleased(evt);
            }
        });

        UserNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtFieldActionPerformed(evt);
            }
        });
        UserNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserNameTxtFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel5.setText("Contact:");

        jLabel6.setText("Email ID:");

        jLabel7.setText("Phone No:");

        mailIdTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailIdTxtFieldActionPerformed(evt);
            }
        });
        mailIdTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailIdTxtFieldKeyReleased(evt);
            }
        });

        phoneTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtFieldActionPerformed(evt);
            }
        });
        phoneTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTxtFieldKeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 51, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel8.setText("Recipe:");

        jLabel9.setText("Recipe Name:");

        jLabel10.setText("No. of Servings:");

        jLabel11.setText("Gluten Free:");

        jLabel12.setText("Difficulty level:");

        btngrpgluten.add(btnGlutenYes);
        btnGlutenYes.setText("Yes");
        btnGlutenYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlutenYesActionPerformed(evt);
            }
        });

        btngrpgluten.add(btnGlutenNo);
        btnGlutenNo.setText("No");
        btnGlutenNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlutenNoActionPerformed(evt);
            }
        });

        jLabel13.setText("No. of Ingredients:");

        jLabel14.setText("Category:");

        jLabel15.setText("Description:");

        jLabel16.setText("Image:");

        imagePathTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePathTxtActionPerformed(evt);
            }
        });

        btnSaveRecipe.setBackground(new java.awt.Color(204, 51, 0));
        btnSaveRecipe.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveRecipe.setText("SAVE RECIPE");
        btnSaveRecipe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSaveRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecipeActionPerformed(evt);
            }
        });

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCheck.setBackground(new java.awt.Color(153, 153, 153));
        btnCheck.setText("SUBMIT");
        btnCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        txtgluten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtglutenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(FrstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameTxtField)
                                    .addComponent(UserNameTxtField))))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearch)
                                            .addComponent(btnSaveRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(recipeTitleTxtField)
                                .addComponent(difficultyTxtField)
                                .addComponent(servingSpinner)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtgluten, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnGlutenNo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnGlutenYes))
                                .addComponent(ingredientSpinner)
                                .addComponent(categoryTxtField)
                                .addComponent(descTxtField)
                                .addComponent(imagePathTxt)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FrstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(mailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(phoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnSave))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(recipeTitleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(servingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnGlutenYes)
                    .addComponent(btnGlutenNo)
                    .addComponent(btnCheck)
                    .addComponent(txtgluten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(difficultyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ingredientSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(categoryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(descTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSaveRecipe)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(imagePathTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FrstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrstNameTxtFieldActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName = FrstNameTxtField.getText();
        String lastName = LastNameTxtField.getText();
        String userName=UserNameTxtField.getText();
        existingUserName.add(userName);
        String mailId = mailIdTxtField.getText();
        long phoneNo = Long.parseLong(phoneTxtField.getText());
        
        
        if(FrstNameTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "First Name cannot be empty");
        } 
        else if(LastNameTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name cannot be empty");
        }
        else if(UserNameTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "User Name cannot be empty");
        }
        else if(mailIdTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Email ID cannot be empty");
        }
        else if(phoneTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Phone Number cannot be empty");
        }
        else{
        this.user.setChefFirstName(firstName);
        this.user.setChefLastName(lastName);
        this.user.setUserName(userName);
   
        Contact contact=this.user.getContact();
        contact.setEmailId(mailId);
        contact.setPhoneNo(phoneNo);
        
        JOptionPane.showMessageDialog(null, "Chef's Detail Saved");
            
        }



        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecipeActionPerformed
        // TODO add your handling code here:
        String recipeName=recipeTitleTxtField.getText();
        int servings=(Integer)servingSpinner.getValue();
        double difficulty=Double.parseDouble(difficultyTxtField.getText());
        int ingredients=(Integer)ingredientSpinner.getValue();
        String category=categoryTxtField.getText();
        String description=descTxtField.getText();
        String Image=imagePathTxt.getText();
        Boolean gluten=false;
        if(txtgluten.getText().equals("Yes")){
            gluten=true;
        }
        
        
        
        if(recipeTitleTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Recipe Name cannot be empty");
        } 
        else if(servingSpinner.getValue().equals("")) {
            JOptionPane.showMessageDialog(null, "No.of Servings has to be specified");
        }
        else if(difficultyTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Difficulty level has to be specified");
        }
        else if(ingredientSpinner.getValue().equals("")) {
            JOptionPane.showMessageDialog(null, "No.of Ingredients has to be specified");
        }
        else if(categoryTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Category cannot be empty");
        }
        else if(descTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Description cannot be empty");
        }
         else if (imagePathTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null," Add Image");
        }
         else{
             Recipe recipe=this.user.createRecipe(recipeName, servings, gluten, difficulty, ingredients, category, description, Image);
             JOptionPane.showMessageDialog(null, "Added Recipe");
         }
        
        
                
    }//GEN-LAST:event_btnSaveRecipeActionPerformed

    private void btnGlutenYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlutenYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGlutenYesActionPerformed

    private void btnGlutenNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlutenNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGlutenNoActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter fnef= new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        JFileChooser browseImageFile= new JFileChooser();
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue==JFileChooser.APPROVE_OPTION){
            File selectedImageFile= browseImageFile.getSelectedFile();
            String selectedImagePath= selectedImageFile.getAbsolutePath();
            
            imagePathTxt.setText(selectedImagePath);
            
            JOptionPane.showMessageDialog(null,selectedImagePath );
            
            ImageIcon i1=new ImageIcon(selectedImagePath);
           
            Image image=i1.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(image));
            
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void LastNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTxtFieldActionPerformed

    private void UserNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTxtFieldActionPerformed

    private void mailIdTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailIdTxtFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mailIdTxtFieldActionPerformed

    private void phoneTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtFieldActionPerformed

    private void txtglutenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtglutenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtglutenActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        if(btnGlutenNo.isSelected()==true){
            txtgluten.setText("No");
        }
        else{
            txtgluten.setText("Yes");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void imagePathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagePathTxtActionPerformed

    private void mailIdTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailIdTxtFieldKeyReleased
        // TODO add your handling code here:
        String e=mailIdTxtField.getText();
        if(e.matches("^[A-Za-z0-9+_.-]+@(.+)$")){
             mailIdTxtField.setBackground(Color.green);
        }
        else{
             mailIdTxtField.setBackground(Color.red);
       }
    }//GEN-LAST:event_mailIdTxtFieldKeyReleased

    private void phoneTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTxtFieldKeyReleased
        // TODO add your handling code here:
        String mn=phoneTxtField.getText();
        
       if(mn.matches("^[0-9 ]*$")&& mn.length()==10){
           phoneTxtField.setBackground(Color.green);
       } 
       else{
             phoneTxtField.setBackground(Color.red);
       }
    }//GEN-LAST:event_phoneTxtFieldKeyReleased

    private void UserNameTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameTxtFieldKeyReleased
        // TODO add your handling code here:
         for(String e : existingUserName){
            if(e.equals(UserNameTxtField.getText())){
                UserNameTxtField.setBackground(Color.red);
            }
            else{
                UserNameTxtField.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_UserNameTxtFieldKeyReleased

    private void LastNameTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTxtFieldKeyReleased
        // TODO add your handling code here:
        String mn=LastNameTxtField.getText();
         if(Pattern.matches("[a-zA-Z]+", mn)){
           LastNameTxtField.setBackground(Color.green);
       } 
       else{
            LastNameTxtField.setBackground(Color.red);
       }
    }//GEN-LAST:event_LastNameTxtFieldKeyReleased

    private void FrstNameTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FrstNameTxtFieldKeyReleased
        // TODO add your handling code here:
         String mn=FrstNameTxtField.getText();
         if(Pattern.matches("[a-zA-Z]+", mn)){
           FrstNameTxtField.setBackground(Color.green);
       } 
       else{
             FrstNameTxtField.setBackground(Color.red);
       }
    }//GEN-LAST:event_FrstNameTxtFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FrstNameTxtField;
    private javax.swing.JTextField LastNameTxtField;
    private javax.swing.JTextField UserNameTxtField;
    private javax.swing.JButton btnCheck;
    private javax.swing.JRadioButton btnGlutenNo;
    private javax.swing.JRadioButton btnGlutenYes;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveRecipe;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup btngrpgluten;
    private javax.swing.JTextField categoryTxtField;
    private javax.swing.JTextField descTxtField;
    private javax.swing.JTextField difficultyTxtField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagePathTxt;
    private javax.swing.JSpinner ingredientSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mailIdTxtField;
    private javax.swing.JTextField phoneTxtField;
    private javax.swing.JTextField recipeTitleTxtField;
    private javax.swing.JSpinner servingSpinner;
    private javax.swing.JTextField txtgluten;
    // End of variables declaration//GEN-END:variables
}
